export interface Fiis {
    nome: string,
    ticker: string,
    cotacao: string,
    dy_12M: string,
    p_vp: string,
    liquidez_diaria: string,
    variacao_12m: string,
    razao_social: string,
    cnpj: string,
    publico_alvo: string,
    mandato: string,
    segmento: string,
    tipo_de_fundo: string,
    prazo_de_duracao: string,
    tipo_de_gestao: string,
    taxa_de_administracao: string,
    vacancia: string,
    numero_de_cotistas: string,
    cotas_emitidas: string,
    val_patrimonial_p_cota: string,
    valor_patrimonial: string,
    ultimo_rendimento: string,
    tipo_ativo?: string,
    views: number,
    nota: string | number,
    indicadores_positivos: string[],
    ultima_atualizacao: string
}
