export const acoesInfos: {reference: string, header: string, color: boolean, tooltip: boolean, show: boolean, alwaysShow: boolean}[] = [
    {reference: "ticker", header: "Ticker", color: false, tooltip: false, show: true, alwaysShow: true},
    {reference: "cotacao", header: "Cotação", color: false, tooltip: false, show: true, alwaysShow: true},
    {reference: "nome", header: "Nome", color: false, tooltip: true, show: true, alwaysShow: true},
    {reference: "variacao_12m", header: "Variação 12M", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "p/l", header: "P/L", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "p/vp", header: "P/VP", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "dy_12m", header: "DY 12M", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "p/receita_psr", header: "P/Receita PSR", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "margem_liquida", header: "Margem Líquida", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "margem_ebit", header: "Margem EBIT", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "roe", header: "ROE", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "roic", header: "ROIC", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "cagr_lucros_5_anos", header: "CAGR Lucros 5 Anos", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "valor_de_mercado", header: "Valor de Mercado", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "patrimonio_liquido", header: "Patrimônio Líquido", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "n_total_de_papeis", header: "Nº Total de Papéis", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "tag_along", header: "Tag Along", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "liquidez_media_diaria", header: "Liquidez Média Diária", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "setor", header: "Setor", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "segmento_de_listagem", header: "Segmento de Listagem", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "segmento", header: "Segmento", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "payout", header: "Payout", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "margem_bruta", header: "Margem Bruta", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "margem_ebitda", header: "Margem EBITDA", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "ev/ebitda", header: "EV/EBITDA", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "ev/ebit", header: "EV/EBIT", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "p/ebitda", header: "P/EBITDA", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "p/ebit", header: "P/EBIT", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "p/ativo", header: "P/Ativo", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "p/capgiro", header: "P/Capgiro", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "p/ativo_circ_liq", header: "P/Ativo Circ Liq", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "vpa", header: "VPA", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "lpa", header: "LPA", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "giro_ativos", header: "Giro Ativos", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "roa", header: "ROA", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "divida_liquida/patrimonio", header: "Dívida Líquida / Patrimônio", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "divida_liquida/ebitda", header: "Dívida Líquida / EBITDA", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "divida_liquida/ebit", header: "Dívida Líquida / EBIT", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "divida_bruta/patrimonio", header: "Dívida Bruta / Patrimônio", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "patrimonio/ativos", header: "Patrimônio / Ativos", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "passivos/ativos", header: "Passivos / Ativos", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "liquidez_corrente", header: "Liquidez Corrente", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "cagr_receitas_5_anos", header: "CAGR Receitas 5 Anos", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "valor_de_firma", header: "Valor de Firma", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "ativos", header: "Ativos", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "ativo_circulante", header: "Ativo Circulante", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "divida_bruta", header: "Dívida Bruta", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "divida_liquida", header: "Dívida Líquida", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "disponibilidade", header: "Disponibilidade", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "free_float", header: "Free Float", color: true, tooltip: false, show: false, alwaysShow: false}
]

export const fiisInfos: {reference: string, header: string, color: boolean, tooltip: boolean, show: boolean, alwaysShow: boolean}[] = [
    {reference: "ticker", header: "Ticker", color: false, tooltip: false, show: true, alwaysShow: true},
    {reference: "cotacao", header: "Cotação", color: false, tooltip: false, show: true, alwaysShow: true},
    {reference: "nome", header: "Nome", color: false, tooltip: true, show: true, alwaysShow: true},
    {reference: "dy_12M", header: "DY 12M", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "liquidez_diaria", header: "Liquidez Diária", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "variacao_12m", header: "Variação 12M", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "segmento", header: "Segmento", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "tipo_de_fundo", header: "Tipo de Fundo", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "taxa_de_administracao", header: "Taxa de Administração", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "vacancia", header: "Vacância", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "numero_de_cotistas", header: "Número de Cotistas", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "cotas_emitidas", header: "Cotas Emitidas", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "val_patrimonial_p/cota", header: "Valor Patrimonial/Cota", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "valor_patrimonial", header: "Valor Patrimonial", color: true, tooltip: false, show: true, alwaysShow: true},
    {reference: "ultimo_rendimento", header: "Último Rendimento", color: false, tooltip: false, show: true, alwaysShow: true},
    {reference: "razao_social", header: "Razão Social", color: false, tooltip: true, show: false, alwaysShow: false},
    {reference: "cnpj", header: "CNPJ", color: false, tooltip: false, show: false, alwaysShow: false},
    {reference: "publico-alvo", header: "Público Alvo", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "mandato", header: "Mandato", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "prazo_de_duracao", header: "Prazo de Duração", color: true, tooltip: false, show: false, alwaysShow: false},
    {reference: "tipo_de_gestao", header: "Tipo de Gestão", color: true, tooltip: false, show: false, alwaysShow: false}
]
